# Generated by Django 4.1.3 on 2022-11-16 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 5, 31, 0, 349980, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
